import vgamepad as vg

"""
Data and mappings that are useful across the project
"""

#all the xbox buttons
vg_buttons_xbox = [
    vg.XUSB_BUTTON.XUSB_GAMEPAD_A,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_B,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_X,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_Y,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_BACK,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_GUIDE,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_START
]

#map from xbox buttons to ds4 buttons (vigembus)
xbox_to_ds4_vigembus = {
    #normal (.press_button/release_button)
    vg.XUSB_BUTTON.XUSB_GAMEPAD_A : vg.DS4_BUTTONS.DS4_BUTTON_CROSS,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_B : vg.DS4_BUTTONS.DS4_BUTTON_CIRCLE, 
    vg.XUSB_BUTTON.XUSB_GAMEPAD_X : vg.DS4_BUTTONS.DS4_BUTTON_SQUARE,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_Y : vg.DS4_BUTTONS.DS4_BUTTON_TRIANGLE,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER : vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_LEFT,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER : vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_RIGHT,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB : vg.DS4_BUTTONS.DS4_BUTTON_THUMB_LEFT,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB : vg.DS4_BUTTONS.DS4_BUTTON_THUMB_RIGHT,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_BACK : vg.DS4_BUTTONS.DS4_BUTTON_SHARE,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_START : vg.DS4_BUTTONS.DS4_BUTTON_OPTIONS,
    #dpad (.directional_pad/.directional_pad(DS4_BUTTON_DPAD_NONE))
    vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP : vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTH,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN : vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTH,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT : vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_WEST,
    vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT : vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_EAST,
    #special (.press_special_button/release_special_button)
    vg.XUSB_BUTTON.XUSB_GAMEPAD_GUIDE : vg.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_PS,
}

#ds4 virtual controller dpad buttons
ds4_special_buttons = [
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTH,
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTH,
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_WEST,
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_EAST,
]

#map from ds4 buttons to xbox (vigembus)
ds4_to_xbox_vigembus = {value: key for key, value in xbox_to_ds4_vigembus.items()}

#from ps4 joystick_button index to vigembus xbox 360 button
ps4_button_index_to_360 = {
    #main buttons
    0 : vg.XUSB_BUTTON.XUSB_GAMEPAD_A,
    1 : vg.XUSB_BUTTON.XUSB_GAMEPAD_B,
    2 : vg.XUSB_BUTTON.XUSB_GAMEPAD_X,
    3 : vg.XUSB_BUTTON.XUSB_GAMEPAD_Y,
    #bumpers
    9  : vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER,
    10 : vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER,
    #d-pad
    11 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP,
    12 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN,
    13 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT,
    14 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT,
    #sticks
    7 : vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB,
    8 : vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB,
    #menus
    4 : vg.XUSB_BUTTON.XUSB_GAMEPAD_BACK,
    5 : vg.XUSB_BUTTON.XUSB_GAMEPAD_GUIDE,
    6 : vg.XUSB_BUTTON.XUSB_GAMEPAD_START,
}

#from vigembus 360 button to ps4 joystick index
button_to_ps4_index = {value: key for key, value in ps4_button_index_to_360.items()}

#from xbox one joystick_button index to vigembus xbox 360 button
xbox_button_index_to_360 = {
    #main buttons
    0 : vg.XUSB_BUTTON.XUSB_GAMEPAD_A,
    1 : vg.XUSB_BUTTON.XUSB_GAMEPAD_B,
    2 : vg.XUSB_BUTTON.XUSB_GAMEPAD_X,
    3 : vg.XUSB_BUTTON.XUSB_GAMEPAD_Y,
    #bumpers
    4  : vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER,
    5 : vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER,
    #d-pad
    12 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP,
    13 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN,
    14 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT,
    15 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT,
    #sticks
    8 : vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB,
    9 : vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB,
    #menus
    6 : vg.XUSB_BUTTON.XUSB_GAMEPAD_BACK,
    11 : vg.XUSB_BUTTON.XUSB_GAMEPAD_GUIDE,
    7 : vg.XUSB_BUTTON.XUSB_GAMEPAD_START,
}

#from vigembus 360 button to xbox one joystick index
button_to_xbox_index = {value: key for key, value in xbox_button_index_to_360.items()}

#all the ds4 buttons
vg_buttons_ds4 = [
    #normal
    vg.DS4_BUTTONS.DS4_BUTTON_THUMB_RIGHT,
    vg.DS4_BUTTONS.DS4_BUTTON_THUMB_LEFT,
    vg.DS4_BUTTONS.DS4_BUTTON_OPTIONS,
    vg.DS4_BUTTONS.DS4_BUTTON_SHARE,
    vg.DS4_BUTTONS.DS4_BUTTON_TRIGGER_RIGHT,
    vg.DS4_BUTTONS.DS4_BUTTON_TRIGGER_LEFT,
    vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_RIGHT,
    vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_LEFT,
    vg.DS4_BUTTONS.DS4_BUTTON_TRIANGLE,
    vg.DS4_BUTTONS.DS4_BUTTON_CIRCLE,
    vg.DS4_BUTTONS.DS4_BUTTON_CROSS,
    vg.DS4_BUTTONS.DS4_BUTTON_SQUARE,
    #special
    vg.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_PS,
    # vg.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_TOUCHPAD,
    #d-pad
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NONE,
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_WEST,
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTH,
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_EAST,
    vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTH,
    # vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTHWEST,
    # vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTHWEST,
    # vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTHEAST,
    # vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTHEAST,
]